

services:
  app:
    build: .
    container_name: app
    ports:
      - "8080:8080"
    environment:
      - DB_URL=jdbc:postgresql://db:5432/taskTracker
      - APP_AVATAR_DIR=/app/avatars
    volumes:
      - avatars_volume:/app/avatars
    depends_on:
      - db
      - redis


  db:
    image: 'postgres'
    container_name: 'db'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    expose:
      - '5432'
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: qwe
      POSTGRES_DB: taskTracker

  redis:
    image: redis:latest
    container_name: redis
    restart: "always"

    expose:
      - "6379"
    command: redis-server --appendonly yes


volumes:  # Объявляем все volumes
  avatars_volume:
  postgres_data:
