

services:
  app:
    build: .
    container_name: app
    ports:
      - "8080:8080"
    environment:
      - DB_URL=jdbc:postgresql://db:5432/taskTracker
    depends_on:
      - db
      - redis


  db:
    image: 'postgres'
    container_name: 'db'

    expose:
      - '5432'
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: qwe
      POSTGRES_DB: taskTracker

  redis:
    image: redis:latest
    restart: "always"

    ports:
      - "6379:6379"
    command: redis-server --appendonly yes



